name: reviewdog
on: [pull_request]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: stylelint-github
        uses: reviewdog/action-stylelint@3957468a0ecd893d96e59774122c860fa98b0f82 # v1.30.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: eslint
        uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd # v1.33.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: 'main.js'
